ingress:
  tls:
    enabled: true
    secretName: "svajlenka-prod.local-tls"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"

service:
  additionalHosts:
    - svajlenka.ineedto.party
    - svajlenka.com
    - www.svajlenka.com
  commonName: svajlenka.com