name: Static site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: deploy src to gh-pages
      run: |
        git config --global user.name 'Chris Svajlenka'
        git config --global user.email 'chris@svajlenka.com'
        git push origin `git subtree split --prefix src master`:gh-pages --force

